import { BasicEnumBuilder } from 'better-ts-enum/basic-enum'

export const InterestNameEnum = BasicEnumBuilder.new({ valueType: 'key' })
  .$('Reading')
  .$('Coding')
  .$('Music')
  .$('Photography')
  .$('Fitness')
  .$('Movies')
  .$('Gaming')
  .$('Cooking')
  .$('ArtDesign', 'Art & Design')
  .$('Travel')
  .$('Debate')
  .$('Sports')
  .$('Entrepreneurship')
  .$('Writing')
  .$('Fashion')
  .$('DataScience', 'Data Science')
  .$('Volunteering')
  .$('Dance')
  .$('FaithSpirituality', 'Faith & Spirituality')
  .$('Poetry')
  .build()
export type InterestNameEnum = typeof InterestNameEnum.$.infer.values
